### ISSUE TITLE
some questions about the data

### ISSUE THREAD

**Issue by XiaohanChen97** [cole-trapnell-lab/sci-plex#1]
This is really a nice work! But I got some questions about the data.
First, I saw this in your code, but I can not find CDS file in GEO.
![image](https://user-images.githubusercontent.com/45548226/71051263-abcc9d00-2182-11ea-9c3c-0aaa14df2c6f.png)
Second, I do want to know which file stores the gene expression matrix in each cell, is the CDS file？
Thank you for such a nice work!

**Comment by sanjayrsrivatsan** [comment]
Hi XiaohanChen97,
I just checked and you're right. I'm trying to figure out why these files weren't uploaded to GEO. I'll leave this ticket open until I confirm with you that the CDS are posted.

**Comment by jamestwebber** [comment]
The method and results are very impressive, this should be a great resource. I have another data question, apologies if this is listed somewhere but I couldn't find it.

Is there conventional dose-response data available for these cell lines and drugs? I see the Fig 4 comparison between sciPlex and _in vitro_ IC50 for the HDAC inhibitors, but was unclear on whether the same type of data were available for the other drugs, and whether those data is in this repo or needs to be retrieved from another source (LINCS?).

**Comment by sanjayrsrivatsan** [comment]
Hi @XiaohanChen97, 
Thanks again for pointing this out. We emailed GEO and the CDS is now online. Please look here for a zipped copy.

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4150377

**Comment by sanjayrsrivatsan** [comment]
@jamestwebber we were able to manually curate the in vitro IC50 data for different HDAC inhibitors against different HDAC isoforms, however, we don't have other conventional dose-response data within the paper itself. What we do have is dose response data based on cell counts as presented in figure3. These are not gold standard estimates for estimating EC50, however, as they only include 4 doses. 

LINCS may be a good place to find this.
